let suggestions = [
    "Multimedia :Computing ,Communication & App",
    "Database systems : design, implementation & management",
    "Systems Programming and Operating Systems",
    "Data Communication & Networking(Forouzan) ",
    "Data and computer communication",
    "Discrete Structures",
    "Data structures & files",
    "Data structure & Algorithms",
    "Financial & industrial management",
    "Visual basic 6 programming : black book",
    "Effective methods for software testing",
    "Multimedia production Planning",
    "Web technologies : tcp/ip, architecture & java programming",
    "Multimedia production Planning",
    "Fundamentals of multimedia",
    "Programming Languages",
    "Data warehousing in the real world",
    "Compiler Design in c",
    "Mobile computing technology, applications & service creation(Talukdar)",
    "Data communications",
    "Data communications and Distributed Networks",
    "Software Maintenance",
    "TCP/IP Illustrated VOL-1",
    "Distributed Systems: concepts & design",
    "Inside CORBA",
    "Distributed Operating Systems",
    "Modern Information Retrieval",
    "Bioinformatics :methods & applications",
    "Cryptography and Network Security",
    "Artificial intelligence (Charniak Eugene)",
    "Computer Organization & Architecture(Stalling)",
    "Distributed Operating Systems",
    "Introduction to Artificial Neural Systems",
    "Network Security private communication in a public world",
    "Artificial Intelligence",
    "Object Oriented Modelling And Design",
    "Bioinformatics Computing",
    "Theory & problems of computer graphics (Plastock)",
    "System Software",
    "Principles of web design",
    "Communication networking an analytical approach",
    "Principles of soft computing",
    "Practical Java projects for beginners",
    "SQL & PL/SQL for oracle 10g",
    "Learning C++",
    "Operating Systems",
    ".Net Programming (Visual Studio 2005)",
    "Java for professionals",
    "Elements of Artificial Neural Networks",
    "Introduction to information system",
    "C# 2008 programming covering .net 3.5",
    "Professional ASP.Net 3.5 security membership & role management with C# & VB",
    "Data Structure & algorithms in Java(Lafore)",
    "Data structures & algorithms in C++",
    "Software testing & analysis: process,principles & techniques",
    "TCP/IP",
    "Data Structure & Algorithms(Aho)",
    "Magnifying C",
    "Mobile computing technology, applications & service creation(Talukdar)",
    "Advanced MS-DOS Programming",
    "Concepts of programming languages",
    "Operating System concepts(Silberschatz)",
    "Concepts of programming languages",
    "Engineering A Compiler",
    "Concepts of programming languages",
    "UNIX Internals",
    "Programming with C",
    "Data Structures & Algorithm Analysis in C++",
    "Data structure : A pseudocode approach with C ++",
    "Compiler construction : principles & practice",
    "Database system Concepts(Peter Rob)",
    "Windows Hacking",
    "E-Mail Hacking",
    "Multimedia Making IT Work",
    "Management Information Systems(OBrian)",
    "Distributed Operating Systems Concepts and Design",
    "Unofficial Guide to Ethical Hacking",
    "Ethical Guide to Hacking mobile phones",
    "Network Security : A Hackers perspective",
    "Beginning Linux programming",
    "Computer Organization & Architecture(Stalling)",
    "Data & Computer Communication",
    "Applied Cryptography: protocols algorithms & source code in C",
    "Procedural Elements For computer graphics",
    "Theory & problems of computer graphics (Plastock)",
    "Systems Programming",
    "System Programming and Operating System and programming",
    "Mobile communications Engineering:Theory & applications",
    "Advanced computer ArchitectureL: parallelalism,scalabilaty & programming",
    "Introduction to computer security",
    "Mobile communications",
    "Programming Windows 5th ED",
    "Hacking Exposed Network Security Secrets & Solutions W/DVD",
    "Management Information System(Jawadekar)",
    "Web Services: An introduction",
    "Core Java Vol 1: Fundamentals",
    "Programming in C",
    "Compiler Design",
    "Parallel computers architecture & Programming",
    "Core Java Vol 1: Fundamentals",
    "Best practice financial management",
    "The Complete Reference HTML & XHTML",
    "Data wearhousing fundamentals : a comprehensive guide for IT professionals",
    "Professional hibernate",
    "Introduction to information technology",
    "Communication Networks",
    "ASP.NET 2.0",
    "Fundametals of database management systems",
    "Principles of Multimedia",
    "IT project management",
    "GMAT : Graduate management admission test",
    "Systems Programming and Operating Systems",
    "Management Information Systems((Robert)",
    "Unix programming : the first drive",
    "Beginning ASP.NET 3.5 in c# And VB",
    "Beginning microsoft Visual c# 2008",
    "Beginning microsoft visual basic 2008",
    "SQL, PL/SQL The programming language of oracle",
    "Data communications and computer networks",
    "Unix Network Programming",
    "Professional ASP.NET 3.5 (SP1) in C# & VB",
    "Professional ASP.Net 3.5 security membership & role management with C# & VB",
    "Professional linux kernel architecture",
    "Software quality engineering testing, quality assurance & quantifiable improvement",
    "C and data structures",
    "Shell scripting recipes : a problem-solution approach",
    "Professional microsoft SQL server 2008 administration",
    "Information storage & retrieval",
    "Beginning Ajax with Asp.Net",
    "Head first object oriented analysis & design",
    "Head first stastistics",
    "Java server programming for professionals",
    "Programming embedded systems in c & c++",
    "Java server pages project for beginners",
    "C for beginners",
    "Java for professionals",
    "Head first Java",
    "Java servelt & Jsp cookbook",
    "Real Time systems (Liu)",
    "Foundations of programming languages : design & implementation",
    "Developing web applications",
    "Mastering visual basic 6",
    "Advanced computer architectures",
    "Data Structures ,Algorithms and object oriented programming",
    "Guide to operating system security",
    "Theory & problems of computer graphics (Plastock)",
    "System Programing",
    "Advanced MS-DOS Programming",
    "Data structure & algorithms in Java",
    "Computer communications and networking technologies",
    "Java actually : a first course in programming",
    "System Programing",
    "Software Metrices",
    "Ethical hacking guide to corporate security",
    "Quality software project management",
    "Introduction to parallel computing",
    "Structs 2 : blackbook",
    "Ajax : blackbook",
    "Core Servlets & Java Server pages: vol I:core technologies",
    "Introduction to Automata Theory, Languages & Computation",
    "Unix programming environment",
    "Engineering approach to computer networking",
    "XML from A TO Z",
    "Real Time systems (Liu)",
    "Concepts of programming languages",
    "Mobile communications",
    "Computer Organization & Architecture(Stalling)",
    "Compilers : Principles ,Techniques & tools",
    "UML 2 and and the unified process : practical object oriented analysis & design",
    "computer networks & internals with internet applications",
    "Database Systems : A Practical approach to design",
    "Distributed Systems: concepts & design",
    "Data Mining : introductory & advanced topics",
    "Thinking in Java",
    "Fundamentals of Database systems (Elmasai)",
    "Programming embedded systems in c & c++",
    "Java servlets & JSP",
    "Java server pages project for beginners",
    "Head first c#",
    "Software Testing Tools",
    "Java server programming for professionals",
    "Distributed systems architecture: a middle approach",
    "Computers as components: principles of embeded computing system design",
    "Comprehensive C++ Programming",
    "Data Structure & Algorithms(Aho)",
    "UML 2 and and the unified process : practical object oriented analysis & design",
    "Comprehensive C++ Programming",
    "Data structures & algorithms in Java",
    "Programming logic & design comprehensive",
    "Comprehensive C++ Programming",
    "Introduction To Languages and theory of computation",
    "High Speed Networks & Internets Performance & Quality of Service",
    "Theory of computation",
    "Complete reference C",
    "Operating system Concepts 6th ED",
    "Computers as components: principles of embeded computing system design",
    "Organizational behavior ( Luthans Fred)",
    "TCP/IP Protocol suite",
    "Object Oriented modeling & design with UML",
    "Operating system concepts",
    "Multimedia Communication System",
    "Mastering visual basic 6",
    "UNIX Systems Programming",
    "Management Information System(Jawadekar)",
    
















];
